name: Terraform CI/CD

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: ${{ secrets.TERRAFORM_S3_BUCKET }}
      TF_VERSION: 1.12.2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install Tools
        run: |
          curl -sSfL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          export PATH="$HOME/bin:$PATH"
          infracost --version
          curl -sL https://raw.githubusercontent.com/cloudskiff/driftctl/release/latest/install.sh | bash

      - name: Terraform Init
        run: terraform init

      - name: Run TFLint
        run: tflint --init && tflint

      - name: Run Checkov
        run: checkov -d . -o json > checkov-report.json

      - name: Run Infracost
        run: |
          infracost breakdown --path . \
            --format json \
            --out-file infracost-report.json

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary && terraform show -json tfplan.binary > plan.json

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary

      - name: Upload Reports to S3
        run: |
          aws s3 cp checkov-report.json s3://${{ env.S3_BUCKET }}/checkov-report.json
          aws s3 cp infracost-report.json s3://${{ env.S3_BUCKET }}/infracost-report.json
          aws s3 cp plan.json s3://${{ env.S3_BUCKET }}/plan.json

      - name: Run Drift Detection (Optional)
        run: |
          driftctl scan --from tfstate+s3://my-tfstate-bucket/path --output json > drift-report.json
          aws s3 cp drift-report.json s3://${{ env.S3_BUCKET }}/drift-report.json
